#!/usr/bin/env python3
"""
fonts.py — pull the webfonts into the repo so game night doesn't need Google.

    python3 tools/fonts.py            # -> static/fonts/ + static/fonts.css

Three reasons this is worth a build step rather than a `<link>`:

- **It can fail at the worst moment.** A blocked request, a captive-portal
  wifi, a DNS hiccup — and the host screen renders the whole game in Times New
  Roman, in front of the one person you built it for.
- **It's a request to Google with her IP on it**, from a page that is otherwise
  entirely between the two of you.
- **It's slow on a cold phone.** Two DNS lookups and two TLS handshakes before
  a single letter of a question appears.

Only the `latin` and `latin-ext` subsets are kept. Together they cover
everything either of you has typed that isn't an emoji, and emoji come from the
phone's own font either way.
"""

from __future__ import annotations

import hashlib
import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "static", "fonts")
CSS = os.path.join(ROOT, "static", "fonts.css")

# The three faces the game uses. Fraunces is variable on the optical-size axis
# and player.html sets `font-variation-settings:"opsz" 40`, so it has to stay
# the variable file rather than a static instance.
FAMILIES = (
    "Fraunces:opsz,wght@9..144,400;9..144,600;9..144,900",
    "Karla:wght@400;500;700",
    "Space+Mono:wght@400;700",
)
URL = ("https://fonts.googleapis.com/css2?"
       + "&".join(f"family={f}" for f in FAMILIES) + "&display=swap")

# Without a browser UA the API serves ttf, which is roughly twice the bytes.
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

KEEP = ("latin", "latin-ext")
BLOCK = re.compile(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})", re.S)
FIELD = {k: re.compile(rf"{k}:\s*([^;]+);") for k in
         ("font-family", "font-style", "font-weight", "unicode-range")}
SRC = re.compile(r"url\((https://[^)]+\.woff2)\)")

G, Y, D, B, X = "\033[32m", "\033[33m", "\033[2m", "\033[1m", "\033[0m"


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def slug(family: str, weight: str, subset: str) -> str:
    fam = family.strip().strip("'\"").lower().replace(" ", "-")
    return f"{fam}-{weight.strip().replace(' ', '')}-{subset}.woff2"


def main() -> None:
    os.makedirs(OUT, exist_ok=True)
    print(f"\n  {B}fonts{X}  {D}{URL[:72]}…{X}\n")
    css = fetch(URL).decode("utf-8")

    # A variable font is served once per weight you asked for, and it's the
    # same file every time — Fraunces 400, 600 and 900 are one 66 kB download
    # repeated three times. Group by what actually came back rather than by
    # what was asked for, and declare a weight *range* over the single file.
    seen: dict[str, bytes] = {}
    groups: dict[tuple, list[str]] = {}
    ranges: dict[tuple, str] = {}
    order: list[tuple] = []

    for subset, body in BLOCK.findall(css):
        if subset not in KEEP:
            continue
        m = SRC.search(body)
        if not m:
            continue
        got = {k: (r.search(body).group(1).strip() if r.search(body) else "")
               for k, r in FIELD.items()}
        if m.group(1) not in seen:
            seen[m.group(1)] = fetch(m.group(1))
        data = seen[m.group(1)]
        key = (got["font-family"], got["font-style"], subset,
               hashlib.sha256(data).hexdigest()[:8])
        if key not in groups:
            groups[key] = []
            order.append(key)
        groups[key].append(got["font-weight"])
        ranges[key] = got["unicode-range"]

    if not groups:
        raise SystemExit(f"{Y}nothing came back — check the URL{X}")

    for stale in os.listdir(OUT):                 # last run's duplicates
        if stale.endswith(".woff2"):
            os.remove(os.path.join(OUT, stale))

    by_digest = {hashlib.sha256(d).hexdigest()[:8]: d for d in seen.values()}
    lines = [
        "/* Self-hosted. Generated by tools/fonts.py — don't hand-edit.",
        " *",
        " * The game does not ask Google for anything at run time: not on a",
        " * captive-portal wifi, not with her IP attached, and not before the",
        " * first letter of the first question appears.",
        " */",
        "",
    ]
    total = 0
    for key in order:
        family, style, subset, digest = key
        weights = sorted({int(w) for w in groups[key]})
        data = by_digest[digest]
        name = slug(family, str(weights[0]) if len(weights) == 1 else "var",
                    subset)
        with open(os.path.join(OUT, name), "wb") as f:
            f.write(data)
        total += len(data)
        weight = (str(weights[0]) if len(weights) == 1
                  else f"{weights[0]} {weights[-1]}")
        print(f"  {G}↓{X} {name:38} {len(data) / 1024:6.1f} kB  "
              f"{D}weight {weight}{X}")
        lines += [
            f"/* {subset} */",
            "@font-face {",
            f"  font-family: {family};",
            f"  font-style: {style};",
            f"  font-weight: {weight};",
            "  font-display: swap;",
            f"  src: url(/static/fonts/{name}) format('woff2');",
            f"  unicode-range: {ranges[key]};",
            "}",
            "",
        ]

    with open(CSS, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"\n  {len(order)} files · {total / 1024:.0f} kB total")
    print(f"  {G}static/fonts.css{X}  {D}link it instead of fonts.googleapis.com{X}\n")


if __name__ == "__main__":
    main()
